# Numpy Tutorial

In [1]:
import numpy as np

In [2]:
myarray=np.array([[1,2,3],[4,5,6],[7,8,9]], np.int64)

In [3]:
myarray[1,2]

6

In [4]:
myarray.dtype

dtype('int64')

In [5]:
myarray.shape

(3, 3)

In [6]:
myarray[1,2]=45

In [7]:
myarray

array([[ 1,  2,  3],
       [ 4,  5, 45],
       [ 7,  8,  9]], dtype=int64)

# Conversion from other Python structures

In [8]:
myarray.shape

(3, 3)

In [9]:
myarray.dtype

dtype('int64')

In [10]:
myarray.size

9

In [11]:
zeros=np.zeros((2,4))

In [12]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
rng= np.arange(10)

In [14]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
lspace=np.linspace(2,20,10)

In [16]:
lspace

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [17]:
emp=np.empty((4,6))

In [18]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.15710427e-306, 6.89808207e-307, 6.23061763e-307],
       [2.22526399e-307, 6.23053614e-307, 7.56592338e-307,
        1.60216183e-306, 7.56602523e-307, 3.56043054e-307],
       [1.37961641e-306, 2.22518251e-306, 1.33511969e-306,
        6.23036978e-307, 6.23053954e-307, 9.34609790e-307],
       [8.45593934e-307, 9.34600963e-307, 1.86921143e-306,
        6.23061763e-307, 8.45590539e-307, 8.34445562e-308]])

In [19]:
emp_like=np.empty_like(lspace)

In [20]:
emp_like

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [21]:
ide=np.identity(4)

In [22]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
arr=np.arange(99)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [25]:
arr= arr.reshape(3,33)

In [26]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [27]:
arr.shape

(3, 33)

In [28]:
arr=arr.ravel()

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
arr.shape

(99,)

In [31]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [32]:
ar=np.array(x)

In [33]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
ar.sum(axis=0)

array([12, 15, 18])

In [35]:
ar.sum(axis=1)

array([ 6, 15, 24])

# Transpose of Matrix

In [36]:
ar.T 

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [52]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:


b=a.T
b


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [39]:
np.matmul(a,b)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [54]:
c=b-a
c

array([[ 0,  2,  4],
       [-2,  0,  2],
       [-4, -2,  0]])

In [55]:
c=b+a
c

array([[ 2,  6, 10],
       [ 6, 10, 14],
       [10, 14, 18]])

In [56]:
c=b/a
c

array([[1.        , 2.        , 2.33333333],
       [0.5       , 1.        , 1.33333333],
       [0.42857143, 0.75      , 1.        ]])

# Practice Session

In [41]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.dtype

dtype('int32')

In [42]:
a.shape

(3, 3)

In [43]:
a=np.zeros((2,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
b=np.identity(5)
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
c=np.arange(20)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [46]:
d=c.reshape(5,4)
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [47]:
d=d*100
d

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100],
       [1200, 1300, 1400, 1500],
       [1600, 1700, 1800, 1900]])

In [48]:
f=np.linspace(2,50,25)
f

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24., 26.,
       28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50.])

In [49]:
g=np.empty((4,6))
g

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.15710427e-306, 6.89808207e-307, 6.23061763e-307],
       [2.22526399e-307, 6.23053614e-307, 7.56592338e-307,
        1.60216183e-306, 7.56602523e-307, 3.56043054e-307],
       [1.37961641e-306, 2.22518251e-306, 1.33511969e-306,
        6.23036978e-307, 6.23053954e-307, 9.34609790e-307],
       [8.45593934e-307, 9.34600963e-307, 1.86921143e-306,
        6.23061763e-307, 8.45590539e-307, 8.34445562e-308]])